// It is generated by the Firebase CLI.
//
// To generate this file, run the following command in your project's root directory:
//
// flutterfire configure
class DefaultFirebaseOptions {
  static var currentPlatform;
}
